# Generated by Django 4.0 on 2021-12-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_viewer_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
