# Generated by Django 3.2.10 on 2021-12-19 08:35

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_viewer_app", "0002_remove_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "500x500",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
    ]
