# Generated by Django 3.2.10 on 2021-12-19 09:17

import pathlib

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_viewer_app", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=pathlib.PureWindowsPath("/assets/images/no_image.png"),
                upload_to="products/%Y/%m/%d",
            ),
        ),
    ]
