# Generated by Django 3.2.10 on 2021-12-19 10:22

import pathlib

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_viewer_app", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=image_cropping.fields.ImageCropField(
                default=pathlib.PureWindowsPath("/assets/images/no_image.png"),
                upload_to="products/%Y/%m/%d",
            ),
        ),
    ]
