# Generated by Django 3.2.10 on 2021-12-19 10:53

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_viewer_app", "0007_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "1000x1000",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="Обрезать изображение",
            ),
        ),
        migrations.AddField(
            model_name="productdescriptionparagraph",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "1000x1000",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="Обрезать изображение",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "1000x1000",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="Обрезать изображение",
            ),
        ),
    ]
