# Generated by Django 3.2.10 on 2021-12-19 11:26

import pathlib

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_viewer_app", "0008_auto_20211219_1353"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default=pathlib.PureWindowsPath(
                    "C:/Users/rmksr/PycharmProjects/impractical_python/django_shop_3/static/images/no_image.png"
                ),
                null=True,
                upload_to="categories",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default=pathlib.PureWindowsPath(
                    "C:/Users/rmksr/PycharmProjects/impractical_python/django_shop_3/static/images/no_image.png"
                ),
                upload_to="products/%Y/%m/%d",
                verbose_name="Изображение",
            ),
        ),
    ]
