# Generated by Django 4.0 on 2021-12-18 07:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenericPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="Название")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "text",
                    ckeditor.fields.RichTextField(null=True, verbose_name="Текст"),
                ),
                (
                    "main_image",
                    models.ImageField(upload_to="generic_pages", verbose_name="Изображение"),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Последнее обновление"),
                ),
            ],
            options={
                "verbose_name": "Инфостраница",
                "verbose_name_plural": "Инфостраницы",
                "index_together": {("id", "slug")},
            },
        ),
    ]
