# Generated by Django 3.2.10 on 2021-12-19 10:59

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generic_pages_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericpage",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "main_image",
                "1000x400",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="Обрезать изображение",
            ),
        ),
    ]
