# Generated by Django 3.2.10 on 2021-12-19 11:03

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("generic_pages_app", "0002_genericpage_cropping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genericpage",
            options={"verbose_name": "Страница", "verbose_name_plural": "Страницы"},
        ),
        migrations.AlterField(
            model_name="genericpage",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "main_image",
                "1000x300",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="Обрезать изображение",
            ),
        ),
    ]
